name: Build and Release dlib Wheels Gracefully

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_wheels_x86:
    name: Build x86_64 wheels
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone dlib
        run: |
          git clone --depth 1 https://github.com/davisking/dlib.git dlib_src

      - name: Build x86_64 wheels
        uses: pypa/cibuildwheel@v2.21.0
        with:
          package-dir: dlib_src
        env:
          CIBW_BUILD: cp310-* cp311-* cp312-*
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y cmake3 boost-devel openblas-devel lapack-devel 
            libX11-devel libpng-devel libjpeg-devel 
            libtiff-devel atlas-devel gcc gcc-c++ make git
          CIBW_ENVIRONMENT: "CXXFLAGS='-O2 -g0'"
          
      - name: Upload x86_64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-x86_64
          path: ./wheelhouse/*.whl
          retention-days: 30

  build_wheels_aarch64:
    name: Build aarch64 wheels
    runs-on: ubuntu-latest
    timeout-minutes: 180
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Clone dlib
        run: |
          git clone --depth 1 https://github.com/davisking/dlib.git dlib_src

      - name: Build aarch64 wheels
        uses: pypa/cibuildwheel@v2.21.0
        with:
          package-dir: dlib_src
        env:
          CIBW_BUILD: cp310-* cp311-* cp312-*
          CIBW_ARCHS_LINUX: aarch64
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y cmake3 boost-devel openblas-devel 
            lapack-devel git gcc gcc-c++ make
          CIBW_ENVIRONMENT: "CXXFLAGS='-O2 -g0'"
          
      - name: Upload aarch64 artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: wheels-aarch64
          path: ./wheelhouse/*.whl
          retention-days: 30

  release:
    runs-on: ubuntu-latest
    needs: [build_wheels_x86, build_wheels_aarch64]
    if: always() && startsWith(github.ref, 'refs/tags/') && needs.build_wheels_x86.result == 'success'
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Prepare wheels
        run: |
          mkdir -p wheels
          find artifacts -name "*.whl" -exec cp {} wheels/ \;
          echo "Built wheels:"
          ls -lh wheels/
          
          # Count architectures
          x86_count=$(find wheels -name "*x86_64*.whl" | wc -l)
          aarch64_count=$(find wheels -name "*aarch64*.whl" | wc -l)
          echo "x86_64 wheels: $x86_count"
          echo "aarch64 wheels: $aarch64_count"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: |
            Prebuilt dlib wheels for Linux on Python 3.10, 3.11, and 3.12
            
            **Installation:**
            ```pip install dlib-*.whl```

            Choose the wheel that matches your:
            - Python version (cp310, cp311, or cp312)
            - Architecture (x86_64 or aarch64, if available)
            
            Note: aarch64 wheels may not be available if the build timed out.
          files: wheels/*.whl
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}